import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Next.js + ArcGIS API for JavaScript',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" name='viewport' content='width=device-width initial-scale=1'/>
      </head>
      <body className='p-0 m-0 h-full w-full'>{children}</body>
    </html>
  )
}
